name: 'CodeForge SDK Generation'
description: 'Automatically generate and publish SDKs when your OpenAPI spec changes'

inputs:
  spec_id:
    description: 'CodeForge document instance ID (find in platform UI)'
    required: true
  api_token:
    description: 'CodeForge API token (generate in Account Settings)'
    required: true
  api_url:
    description: 'CodeForge API base URL (override for testing)'
    required: false
    default: 'https://api.code-forge.net'

outputs:
  checks_started:
    description: 'Number of generation checks that were started'
  logs_url:
    description: 'URL to view generation logs on CodeForge'

runs:
  using: 'node20'
  main: 'dist/index.js'
